- name: Preparar entorno Kubernetes y Minikube
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Habilitar servicio Docker
      systemd:
        name: docker
        enabled: yes

    - name: Instalar curl
      apt:
        name: curl
        state: present

    - name: Descargar kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Descargar Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Añadir usuario al grupo docker
      user:
        name: usuario
        groups: docker
        append: yes

    - name: Desactivar protección de archivos regulares
      sysctl:
        name: fs.protected_regular
        value: 0
        sysctl_set: yes
        state: present

    - name: Dar permisos a la carpeta tmp
      file:
        path: /tmp
        mode: '0777'
        recurse: yes



