resources:
  - mysqlsecret.yaml
  - mysqlvolume.yaml
  - mysqldeployment.yaml
  - mysqlservice.yaml
  - wordpressvolume.yaml
  - wordpressdeployment.yaml
  - wordpressexporter.yaml
  - wordpressservice.yaml
