global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9100'] 

  - job_name: wordpress_exporter
    honor_timestamps: true
    scrape_interval: 5s

    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["192.168.49.2:31222"]



