apiVersion: v1
kind: Service
metadata:
  name: wordpress-exporter
  labels:
    app: wordpress
    tier: wp
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: exporter
      protocol: TCP
      port: 11011
      targetPort: 11011
      nodePort: 31222
