apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31165
  selector:
    app: wordpress
    tier: frontend
